### PR TITLE
Welcome screen

### PR DESCRIPTION
**Pull request by itsdamslife**
Added welcome screen empty implementation
@Vinodh-G

### CODE REVIEW

**Comment by gouravnayyar** [comment]
@itsdamslife can we add screenshots?

**Comment by bhanuprakash0024** [comment]
@itsdamslife @gouravnayyar yeah adding screenshots would be great

**Comment by itsdamslife** [comment]
sk-welcome-screen

**Comment by bhanuprakash0024** [comment]
+1

**Comment by Vinodh-G** [comment]
+1

**Pull request merged**
